#python testTMA.py /ssd/Oral/train@256Overlap50/save/helloworld/checkpoints/best_dice.pth /raid10/_datasets/Oral/TMA/IHCHE/tissue_epi_0.3 _real_B.png '/raid10/_datasets/Oral/TMA/IHCHE/retrainOverlap50Result2'
#python testTMANorm.py /ssd/Oral/train@256Overlap50/save/norm/checkpoints/best_dice.pth /raid10/_datasets/Oral/TMA/IHCHE/tissue_epi_0.3 _real_B.png '/raid10/_datasets/Oral/TMA/IHCHE/retrainOverlap50NormResult2'
#python testTMA.py /ssd/Oral/train@256Random40/save/random40/checkpoints/best_dice.pth /raid10/_datasets/Oral/TMA/IHCHE/tissue_epi_0.3 _real_B.png '/raid10/_datasets/Oral/TMA/IHCHE/retrainRandom40Result'
#python testTMA.py /ssd/Oral/train@256Random10Correct/save/random10/checkpoints/best_dice.pth /raid10/_datasets/Oral/TMA/IHCHE/tissue_epi_0.3 _real_B.png '/raid10/_datasets/Oral/TMA/IHCHE/retrainRandom10Result'
CUDA_VISIBLE_DEVICES=0 python -W ignore /mnt/disk1/yuxin/oral_seg/testTMA.py '/mnt/disk1/train_wsi_OnInOut/UCSF/save/base_unet/checkpoints/best_dice.pth' '/mnt/disk1/Oral/TMA_arranged/OSU/masked' '.jpg' 4 '/mnt/disk1/all_pred_mask/UCSF/tma'
CUDA_VISIBLE_DEVICES=0 python -W ignore /mnt/disk1/yuxin/oral_seg/testTMA.py '/mnt/disk1/train_wsi_OnInOut/UCSF/save/base_unet/checkpoints/best_dice.pth' '/mnt/disk1/Oral/TMA_arranged/WU/masked' '.tif' 4 '/mnt/disk1/all_pred_mask/UCSF/tma'
CUDA_VISIBLE_DEVICES=0 python -W ignore /mnt/disk1/yuxin/oral_seg/testWSI.py --model-path '/mnt/disk1/train_wsi_OnInOut/UCSF/save/base_unet/checkpoints/best_dice.pth' --src '/mnt/disk1/Oral/SFVA' --anno-dir '/mnt/disk1/Oral/SFVA/Masks/epi_unet_nonexpert' --net-mag 10 --patch-size 256 --batch-size 2 --save-src-dir '/mnt/disk1/Oral/sfva' --save-result-dir '/mnt/disk1/all_pred_mask/UCSF/sfva' --anno-suffix '_tuned.png' --box-mode 'full' --sub-phase 'sub_slide' --tar-scale 4
CUDA_VISIBLE_DEVICES=0 python -W ignore /mnt/disk1/yuxin/oral_seg/testWSI.py --model-path '/mnt/disk1/train_wsi_OnInOut/UCSF/save/base_unet/checkpoints/best_dice.pth' --src '/mnt/disk1/Oral/Vanderbilt' --anno-dir '/mnt/disk1/Oral/Vanderbilt/Masks/epi_unet_nonexpert' --net-mag 10 --patch-size 256 --batch-size 2 --save-src-dir '/mnt/disk1/Oral/vanderbilt' --save-result-dir '/mnt/disk1/all_pred_mask/UCSF/vumc' --anno-suffix '_tuned.png' --box-mode 'full' --sub-phase 'sub_slide' --tar-scale 4
CUDA_VISIBLE_DEVICES=0 python -W ignore /mnt/disk1/yuxin/oral_seg/testTMA.py '/mnt/disk1/train_wsi_OnInOut/UCSF/save/base_unet/checkpoints/best_dice.pth' '/mnt/disk1/tissue_epi_0.3' '_real_B.png' 1 '/mnt/disk1/all_pred_mask/UCSF/ihc'

CUDA_VISIBLE_DEVICES=0 python -W ignore /mnt/disk1/yuxin/oral_seg/testTMA.py '/mnt/disk1/train_wsi_OnInOut/VUMC/save/base_unet/checkpoints/best_dice.pth' '/mnt/disk1/Oral/TMA_arranged/OSU/masked' '.jpg' 4 '/mnt/disk1/all_pred_mask/VUMC/tma'
CUDA_VISIBLE_DEVICES=0 python -W ignore /mnt/disk1/yuxin/oral_seg/testTMA.py '/mnt/disk1/train_wsi_OnInOut/VUMC/save/base_unet/checkpoints/best_dice.pth' '/mnt/disk1/Oral/TMA_arranged/WU/masked' '.tif' 4 '/mnt/disk1/all_pred_mask/VUMC/tma'
CUDA_VISIBLE_DEVICES=0 python -W ignore /mnt/disk1/yuxin/oral_seg/testWSI.py --model-path '/mnt/disk1/train_wsi_OnInOut/VUMC/save/base_unet/checkpoints/best_dice.pth' --src '/mnt/disk1/Oral/SFVA' --anno-dir '/mnt/disk1/Oral/SFVA/Masks/epi_unet_nonexpert' --net-mag 10 --patch-size 256 --batch-size 2 --save-src-dir '/mnt/disk1/Oral/sfva' --save-result-dir '/mnt/disk1/all_pred_mask/VUMC/sfva' --anno-suffix '_tuned.png' --box-mode 'full' --sub-phase 'sub_slide' --tar-scale 4
CUDA_VISIBLE_DEVICES=0 python -W ignore /mnt/disk1/yuxin/oral_seg/testWSI.py --model-path '/mnt/disk1/train_wsi_OnInOut/VUMC/save/base_unet/checkpoints/best_dice.pth' --src '/mnt/disk1/Oral/UCSF' --anno-dir '/mnt/disk1/Oral/UCSF/Masks/epi_unet_nonexpert' --net-mag 10 --patch-size 256 --batch-size 2 --save-src-dir '/mnt/disk1/Oral/ucsf' --save-result-dir '/mnt/disk1/all_pred_mask/VUMC/ucsf' --anno-suffix '_tuned.png' --box-mode 'full' --sub-phase 'sub_slide' --tar-scale 4
CUDA_VISIBLE_DEVICES=0 python -W ignore /mnt/disk1/yuxin/oral_seg/testTMA.py '/mnt/disk1/train_wsi_OnInOut/VUMC/save/base_unet/checkpoints/best_dice.pth' '/mnt/disk1/tissue_epi_0.3' '_real_B.png' '/mnt/disk1/all_pred_mask/VUMC/ihc'
