%% read the WU TSR(tumor stroma ratio) data
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: WU_n112_Outcome_SP_ratio_filename.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2021/01/15 15:27:42

%% Import the data
[~, ~, raw] = xlsread('/mnt/md0/_datasets/OralCavity/WSI/sfva/SFVA_n36_Outcome_ratio_filename.xlsx','Sheet1');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[1,4,14,15,16,17,18,19,20,31,33,34,35,37]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[54,55]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
SFVAn36OutcomeRatioFilename = table;

%% Allocate imported array to column variable names
SFVAn36OutcomeRatioFilename.ID = stringVectors(:,1);
SFVAn36OutcomeRatioFilename.DateofBx = stringVectors(:,2);
SFVAn36OutcomeRatioFilename.PathTStage7th = stringVectors(:,3);
SFVAn36OutcomeRatioFilename.PathNStage7th = stringVectors(:,4);
SFVAn36OutcomeRatioFilename.OverallPathStage7th = categorical(stringVectors(:,5));
SFVAn36OutcomeRatioFilename.ClinicalTStage7th = stringVectors(:,6);
SFVAn36OutcomeRatioFilename.ClinicalNStage7th = stringVectors(:,7);
SFVAn36OutcomeRatioFilename.ClinicalMStage7th = categorical(stringVectors(:,8));
SFVAn36OutcomeRatioFilename.OverallClinicalStage7th = categorical(stringVectors(:,9));
SFVAn36OutcomeRatioFilename.Recurrence = categorical(stringVectors(:,10));
SFVAn36OutcomeRatioFilename.VitalStatus = categorical(stringVectors(:,11));
SFVAn36OutcomeRatioFilename.DateofDeath = stringVectors(:,12);
SFVAn36OutcomeRatioFilename.ReasonforDeath = stringVectors(:,13);
SFVAn36OutcomeRatioFilename.DateofLastFollowUp = stringVectors(:,14);
SFVAn36OutcomeRatioFilename.epiother_tissue = data(:,1);
SFVAn36OutcomeRatioFilename.epiepiother_tissue = data(:,2);

%% Clear temporary variables
clearvars data raw stringVectors R;

%% univariable analysis%%

TvsS=SFVAn36OutcomeRatioFilename.epiother_tissue;
TSR=SFVAn36OutcomeRatioFilename.epiepiother_tissue;


date_lastFollowUp=datetime(SFVAn36OutcomeRatioFilename.DateofLastFollowUp,'InputFormat', 'yyyy/MM/dd');
date_resection = datetime(SFVAn36OutcomeRatioFilename.DateofBx,'InputFormat', 'yyyy/MM/dd');
date_death = datetime(SFVAn36OutcomeRatioFilename.DateofDeath,'InputFormat', 'yyyy/MM/dd');
followup1=datenum(date_lastFollowUp-date_resection);
followup2=datenum(date_death-date_resection);
followup=max(followup1,followup2);
death_with_disease_status=startsWith(SFVAn36OutcomeRatioFilename.ReasonforDeath,'YES');
%disease_reccurence=WUn112OutcomeSPratiofilename.RegionalFailure=='Yes'|...
%    WUn112OutcomeSPratiofilename.LocalFailure=='Yes'|WUn112OutcomeSPratiofilename.DistMetastasis=='Yes';
%disease_reccurence=SFVAn36OutcomeRatioFilename.Recurrence=='Y';
%cens_recurrence=disease_reccurence==0&SFVAn36OutcomeRatioFilename.VitalStatus=='deceased';
cens_death_with_disease_status=death_with_disease_status==0;

% for disease status
X = [TSR];
[b,logl,H,stats] = coxphfit(X,followup,'censoring',cens_death_with_disease_status);

i=1;
for i=1:1
    fprintf('death with disease p=%.8f,HR ratio(95CI)=%.2f(%.2f-%.2f)\n', stats.p(i),exp(stats.beta(i)),exp(stats.beta(i)-1.96*stats.se(i)),exp(stats.beta(i)+1.96*stats.se(i)));
end
%% for recurrence
%X = [TSR];
%[b,logl,H,stats] = coxphfit(X,followup,'censoring',cens_recurrence);

%i=1;
%for i=1:1
%    fprintf('p=%.8f,HR ratio(95CI)=%.2f(%.2f-%.2f)\n', stats.p(i),exp(stats.beta(i)),exp(stats.beta(i)-1.96*stats.se(i)),exp(stats.beta(i)+1.96*stats.se(i)));
%end

%% PathTStage7th
X = [TSR];
PathTStage7th = SFVAn36OutcomeRatioFilename.PathTStage7th;
Y=PathTStage7th;
Y(~contains(Y, 'T4')&~contains(Y, 'T3')&~contains(Y, 'T2')&~contains(Y, 'T1'))=NaN;
Y(contains(Y, 'T4'))=4;
Y(contains(Y, 'T3'))=3;
Y(contains(Y, 'T2'))=2;
Y(contains(Y, 'T1'))=1;
Y=double(Y);
G=~isnan(Y);
Y=Y(G==1);
X=X(G==1);
[RHO, PVAL] = corr(X,Y, 'Type', 'Spearman');
fprintf('PathTStage7th Spearman corr p=%.8f, rho=%.2f\n', PVAL, RHO);
threshold=median(X);
G1=X>threshold;
G2=X<threshold;
x=Y(G1);
y=Y(G2);
[h,p,ci,stats]= ttest(x,y);
fprintf('PathTStage7th ttest p=%.8f\n', p);
%% PathNStage7th
X = [TSR];
PathNStage7th = SFVAn36OutcomeRatioFilename.PathNStage7th;
Y=PathNStage7th;
Y(~contains(Y, 'N2')&~contains(Y, 'N1')&~contains(Y, 'N0'))=NaN;
Y(contains(Y, 'N2'))=2;
Y(contains(Y, 'N1'))=1;
Y(contains(Y, 'N0'))=0;

Y=double(Y);
G=~isnan(Y);
Y=Y(G==1);
X=X(G==1);
[RHO, PVAL] = corr(X,Y, 'Type', 'Spearman');
fprintf('PathNStage7th Spearman corr p=%.8f, rho=%.2f\n', PVAL, RHO);
threshold=median(X);
G1=X>threshold;
G2=X<threshold;
x=Y(G1);
y=Y(G2);
[h,p,ci,stats]= ttest(x,y);
fprintf('PathNStage7th ttest p=%.8f\n', p);
% %% OverallPathStage7th
% X = [TSR];
% OverallPathStage7th = grp2idx(SFVAn36OutcomeRatioFilename.OverallPathStage7th);
% [b,logl,H,stats] = coxphfit(X,OverallPathStage7th);
% 
% i=1;
% for i=1:1
%     fprintf('OverallPathStage7th p=%.8f,HR ratio(95CI)=%.2f(%.2f-%.2f)\n', stats.p(i),exp(stats.beta(i)),exp(stats.beta(i)-1.96*stats.se(i)),exp(stats.beta(i)+1.96*stats.se(i)));
% end
% %% ClinicalTStage7th
% X = [TSR];
% ClinicalTStage7th = grp2idx(SFVAn36OutcomeRatioFilename.ClinicalTStage7th);
% [b,logl,H,stats] = coxphfit(X,ClinicalTStage7th);
% 
% i=1;
% for i=1:1
%     fprintf('ClinicalTStage7th p=%.8f,HR ratio(95CI)=%.2f(%.2f-%.2f)\n', stats.p(i),exp(stats.beta(i)),exp(stats.beta(i)-1.96*stats.se(i)),exp(stats.beta(i)+1.96*stats.se(i)));
% end
% %% ClinicalNStage7th
% X = [TSR];
% ClinicalNStage7th = grp2idx(SFVAn36OutcomeRatioFilename.ClinicalNStage7th);
% [b,logl,H,stats] = coxphfit(X,ClinicalNStage7th);
% 
% i=1;
% for i=1:1
%     fprintf('ClinicalNStage7th p=%.8f,HR ratio(95CI)=%.2f(%.2f-%.2f)\n', stats.p(i),exp(stats.beta(i)),exp(stats.beta(i)-1.96*stats.se(i)),exp(stats.beta(i)+1.96*stats.se(i)));
% end
% %% ClinicalMStage7th
% X = [TSR];
% ClinicalMStage7th = grp2idx(SFVAn36OutcomeRatioFilename.ClinicalMStage7th);
% [b,logl,H,stats] = coxphfit(X,ClinicalMStage7th);
% 
% i=1;
% for i=1:1
%     fprintf('ClinicalMStage7th p=%.8f,HR ratio(95CI)=%.2f(%.2f-%.2f)\n', stats.p(i),exp(stats.beta(i)),exp(stats.beta(i)-1.96*stats.se(i)),exp(stats.beta(i)+1.96*stats.se(i)));
% end
% %% OverallClinicalStage7th
% X = [TSR];
% OverallClinicalStage7th = grp2idx(SFVAn36OutcomeRatioFilename.OverallClinicalStage7th);
% [b,logl,H,stats] = coxphfit(X,OverallClinicalStage7th);
% 
% i=1;
% for i=1:1
%     fprintf('OverallClinicalStage7th p=%.8f,HR ratio(95CI)=%.2f(%.2f-%.2f)\n', stats.p(i),exp(stats.beta(i)),exp(stats.beta(i)-1.96*stats.se(i)),exp(stats.beta(i)+1.96*stats.se(i)));
% end
%% backup ALL below



% % sex
% X = [sex];
% [b,logl,H,stats] = coxphfit(X,followup,'censoring',cens);
% 
% i=1;
% for i=1:1
%     fprintf('p=%.8f,HR ratio(95CI)=%.2f(%.2f-%.2f)\n', stats.p(i),exp(stats.beta(i)),exp(stats.beta(i)-1.96*stats.se(i)),exp(stats.beta(i)+1.96*stats.se(i)));
% end
% 
% % stage

% X = [stage];
% [b,logl,H,stats] = coxphfit(X,followup,'censoring',cens);
% 
% i=1;
% for i=1:1
%     fprintf('p=%.8f,HR ratio(95CI)=%.2f(%.2f-%.2f)\n', stats.p(i),exp(stats.beta(i)),exp(stats.beta(i)-1.96*stats.se(i)),exp(stats.beta(i)+1.96*stats.se(i)));
% end

%% getting automatic data %%
% 
% data=load('allvariable.mat');
% imgNames=data.TestSetNames;
% 
% data79(:,1)=strrep(data79(:,1),'norm_','');
% imgNames=strrep(imgNames,'.mat','');
% 
% vals=[];
% num=length(data79);
% labels=zeros(num,1);
% for i=1: num
%     val=find(strcmp(data79(i,1),imgNames));
%     labels(i)=data.real_predlabels(val);
% end
% 
% 
% %% multivariable analysis %%
% 
% X = [age sex stage labels];
% [b,logl,H,stats] = coxphfit(X,followup,'censoring',cens);
% 
% i=1;
% for i=1:4
%     fprintf('p=%.8f,HR ratio(95CI)=%.2f(%.2f-%.2f)\n', stats.p(i),exp(stats.beta(i)),exp(stats.beta(i)-1.96*stats.se(i)),exp(stats.beta(i)+1.96*stats.se(i)));
% end
 



